/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_smarttransport_citytransport_rrrrandroid_R4 */

#ifndef _Included_ru_smarttransport_citytransport_rrrrandroid_R4
#define _Included_ru_smarttransport_citytransport_rrrrandroid_R4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_smarttransport_citytransport_rrrrandroid_R4
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_smarttransport_citytransport_rrrrandroid_R4_getMessage
  (JNIEnv *, jobject);

/*
 * Class:     ru_smarttransport_citytransport_rrrrandroid_R4
 * Method:    initWithFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_smarttransport_citytransport_rrrrandroid_R4_initWithFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_smarttransport_citytransport_rrrrandroid_R4
 * Method:    nativePipeSTDERRToLogcat
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_smarttransport_citytransport_rrrrandroid_R4_nativePipeSTDERRToLogcat
  (JNIEnv *, jobject);

/*
 * Class:     ru_smarttransport_citytransport_rrrrandroid_R4
 * Method:    getStopIndexbyId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_smarttransport_citytransport_rrrrandroid_R4_getStopIndexbyId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_smarttransport_citytransport_rrrrandroid_R4
 * Method:    planRoute
 * Signature: (IIZJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_smarttransport_citytransport_rrrrandroid_R4_planRoute
  (JNIEnv *, jobject, jint, jint, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
